In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np


In [ ]:
from google.colab import drive
drive.mount('/content/drive')




Mounted at /content/drive


In [ ]:
file = open("/content/drive/MyDrive/My_file5.txt" , "r")

In [ ]:
pid = []
angle = []
gyro = []




for line in file:
  data = line.split(" ")
  pid.append(float(data[0]))
  angle.append(float(data[1]))
  gyro.append(float(data[2]))
  

N = len(pid)

In [ ]:
train_x = [angle[:int(N*0.8)] , gyro[:int(N*0.8)]]
test_x = [angle[int(N*0.8):N-1], gyro[int(N*0.8):N-1]]
val_x = [angle[int(N*0.8):N-1], gyro[int(N*0.8):N-1]]

train_x = np.transpose(train_x)
test_x = np.transpose(test_x)
val_x = np.transpose(val_x)


train_y = np.transpose([pid[:int(N*0.8)]])
test_y = np.transpose([pid[int(N*0.8):N-1]])
val_y = np.transpose([pid[int(N*0.8):N-1]])





In [ ]:
np.shape(train_x)

(7561, 2)

In [ ]:
model = keras.Sequential([
              # keras.layers.Reshape(target_shape=(2,), input_shape=(None,2)),
              keras.layers.Dense(units=6, activation='linear'),
              keras.layers.Dense(units=3, activation='linear'),
              keras.layers.Dense(units=1, activation='linear'),
                   ])
    

In [ ]:
model.compile(optimizer='adam', 
              loss = tf.losses.MeanSquaredError(),
              metrics=['accuracy'])

In [ ]:
history = model.fit(
    train_x, 
    train_y,
    epochs=25, 
    verbose = 2,
    validation_split = 0.1
   
)

Epoch 1/25
213/213 - 1s - loss: 0.5684 - accuracy: 0.0000e+00 - val_loss: 0.1595 - val_accuracy: 0.0000e+00 - 895ms/epoch - 4ms/step
Epoch 2/25
213/213 - 0s - loss: 0.3247 - accuracy: 0.0000e+00 - val_loss: 0.1508 - val_accuracy: 0.0000e+00 - 376ms/epoch - 2ms/step
Epoch 3/25
213/213 - 0s - loss: 0.3246 - accuracy: 0.0000e+00 - val_loss: 0.1563 - val_accuracy: 0.0000e+00 - 345ms/epoch - 2ms/step
Epoch 4/25
213/213 - 0s - loss: 0.3248 - accuracy: 0.0000e+00 - val_loss: 0.1572 - val_accuracy: 0.0000e+00 - 349ms/epoch - 2ms/step
Epoch 5/25
213/213 - 0s - loss: 0.3247 - accuracy: 0.0000e+00 - val_loss: 0.1527 - val_accuracy: 0.0000e+00 - 355ms/epoch - 2ms/step
Epoch 6/25
213/213 - 0s - loss: 0.3247 - accuracy: 0.0000e+00 - val_loss: 0.1519 - val_accuracy: 0.0000e+00 - 310ms/epoch - 1ms/step
Epoch 7/25
213/213 - 0s - loss: 0.3253 - accuracy: 0.0000e+00 - val_loss: 0.1506 - val_accuracy: 0.0000e+00 - 314ms/epoch - 1ms/step
Epoch 8/25
213/213 - 0s - loss: 0.3248 - accuracy: 0.0000e+00 - val_l

In [ ]:
Lay = []
for layer in model.layers:
    Lay.append(layer)

In [ ]:
m2 = Lay[2].get_weights()
m1 = Lay[1].get_weights()
m0 = Lay[0].get_weights()

In [ ]:
l0 = np.transpose(m0[0])
l1 = np.transpose(m1[0])
l2 = np.transpose(m2[0])

In [ ]:
b0 = np.transpose(m0[1])
b1 = np.transpose(m1[1])
b2 = np.transpose(m2[1])

In [ ]:
input = np.array([[0.12],[0.1]])

In [ ]:
s0 = np.dot(l0,input)


In [ ]:
for i in range(len(b0)):
  s0[i] = s0[i] + b0[i]

In [ ]:
s1 = np.dot(l1,s0)

In [ ]:
for i in range(len(b1)):
  s1[i] = s1[i] + b1[i]

In [ ]:
s2 = np.dot(l2,s1)

In [ ]:
for i in range(len(b2)):
  s2[i] = s2[i] + b2[i]

In [ ]:
print(l0)

[[ 0.42332685 -0.20222105]
 [-0.68782717  0.15276884]
 [-0.73504007  0.04829184]
 [-0.6999695  -0.38863742]
 [-0.15463851  0.11431317]
 [ 0.4975862   0.49425155]]


In [ ]:
print(l1)


[[ 0.24514021 -0.63441986 -0.8702627   0.653707    0.77872163  0.88055533]
 [-0.3653803   0.84004796  0.79240024  0.42975596  0.22249372 -0.18821959]
 [-0.23613094 -0.166874   -0.22761439 -0.13526174 -0.60490125  0.17999525]]


In [ ]:
print(l2)

[[ 0.96543264 -0.6907096  -0.34969094]]


In [ ]:
print(b0)

[ 0.12446024 -0.12310111 -0.12404072  0.1154175   0.12996078  0.12572351]


In [ ]:
print(b1)

[ 0.11932582 -0.12067153 -0.12048591]


In [ ]:
print(b2)

[0.11629402]
